# Generated by Django 5.0 on 2024-02-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnic',
            name='certificates',
            field=models.ManyToManyField(blank=True, null=True, to='API.certificate'),
        ),
        migrations.AlterField(
            model_name='tecnic',
            name='clients',
            field=models.ManyToManyField(blank=True, null=True, to='API.client'),
        ),
        migrations.AlterField(
            model_name='tecnic',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='API.comments'),
        ),
        migrations.AlterField(
            model_name='tecnic',
            name='stars',
            field=models.ManyToManyField(blank=True, null=True, to='API.stars'),
        ),
    ]
