# Generated by Django 5.0 on 2024-02-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_tecnic_certificates_alter_tecnic_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='options_to_give_instalation',
            field=models.CharField(default='Recoger', max_length=20),
        ),
    ]
