# Generated by Django 5.0 on 2024-02-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_client_status_instalation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnic',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tecnic',
            name='location_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
