# Generated by Django 5.0 on 2024-02-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_tecnic_location_lat_tecnic_location_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnic',
            name='business_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tecnic',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tecnic',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
