# Generated by Django 5.0.2 on 2024-02-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_tecnic_business_name_tecnic_city_tecnic_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_accepted_by_manager',
            field=models.CharField(default='Esperando Aprobación', max_length=20),
        ),
    ]
