# Generated by Django 5.0.3 on 2024-03-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_callcenter_token_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callcenter',
            name='token_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='manger',
            name='token_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tecnic',
            name='token_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
