# Generated by Django 5.0.3 on 2024-03-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_alter_callcenter_token_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems_tikets',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='problems'),
        ),
    ]
