# Generated by Django 5.0.3 on 2024-03-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_problems_tikets_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='title_description',
            field=models.CharField(max_length=30),
        ),
    ]
