# Generated by Django 5.0.3 on 2024-03-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_alter_problems_title_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems_tikets',
            name='user_with_problem',
            field=models.CharField(max_length=50),
        ),
    ]
