# Generated by Django 5.0.3 on 2024-03-20 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_alter_problems_tikets_user_with_problem'),
        ('authtoken', '0003_tokenproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnic',
            name='token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authtoken.token'),
        ),
    ]
